import type { TechnicalProfessional } from "../types/technical-team"

export const MOCK_TECHNICAL_TEAM: TechnicalProfessional[] = [
  {
    id: "prof-001",
    name: "Eng. Carlos Silva",
    role: "Projetista Estrutural",
    phone: "(11) 99999-1234",
    registryType: "CREA",
    registryNumber: "123456/SP",
    qualification: "Engenheiro Civil",
    service: "Projeto estrutural completo",
    email: "carlos.silva@email.com",
    status: "active",
  },
  {
    id: "prof-002",
    name: "Arq. Maria Santos",
    role: "Arquiteta Responsável",
    phone: "(11) 98888-5678",
    registryType: "CAU",
    registryNumber: "A78901/SP",
    qualification: "Arquiteta e Urbanista",
    service: "Projeto arquitetônico e coordenação",
    email: "maria.santos@email.com",
    status: "active",
  },
  {
    id: "prof-003",
    name: "Eng. João Oliveira",
    role: "Projetista Hidráulico",
    phone: "(11) 97777-9012",
    registryType: "CREA",
    registryNumber: "234567/SP",
    qualification: "Engenheiro Civil",
    service: "Instalações hidráulicas e sanitárias",
    email: "joao.oliveira@email.com",
    status: "active",
  },
  {
    id: "prof-004",
    name: "Eng. Ana Costa",
    role: "Projetista Elétrica",
    phone: "(11) 96666-3456",
    registryType: "CREA",
    registryNumber: "345678/SP",
    qualification: "Engenheira Elétrica",
    service: "Instalações elétricas e automação",
    email: "ana.costa@email.com",
    status: "active",
  },
  {
    id: "prof-005",
    name: "Eng. Roberto Lima",
    role: "Responsável Técnico",
    phone: "(11) 95555-7890",
    registryType: "CREA",
    registryNumber: "456789/SP",
    qualification: "Engenheiro Civil",
    service: "Responsabilidade técnica da obra",
    email: "roberto.lima@email.com",
    status: "active",
  },
  {
    id: "prof-006",
    name: "Arq. Patricia Ferreira",
    role: "Paisagista",
    phone: "(11) 94444-2345",
    registryType: "CAU",
    registryNumber: "B12345/SP",
    qualification: "Arquiteta Paisagista",
    service: "Projeto paisagístico e jardins",
    email: "patricia.ferreira@email.com",
    status: "active",
  },
]

export const REGISTRY_TYPES = {
  CAU: { label: "CAU", color: "bg-blue-100 text-blue-800" },
  CREA: { label: "CREA", color: "bg-green-100 text-green-800" },
  CFT: { label: "CFT", color: "bg-purple-100 text-purple-800" },
  CRQ: { label: "CRQ", color: "bg-orange-100 text-orange-800" },
  OUTROS: { label: "Outros", color: "bg-gray-100 text-gray-800" },
} as const

export const PROFESSIONAL_ROLES = [
  "Arquiteta Responsável",
  "Projetista Estrutural",
  "Projetista Hidráulico",
  "Projetista Elétrica",
  "Responsável Técnico",
  "Paisagista",
  "Projetista de Ar Condicionado",
  "Projetista de Incêndio",
  "Consultor Ambiental",
  "Coordenador de Projetos",
] as const
